environment:
  matrix:
  # node.js
    - nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - set IS_APPVEYOR_CI=true
  - node -v && npm i -g npm@6.5.0 && npm -v
  - npm install

build_script:
  - npm run build

test_script:
  - npm run test -- -t es5 -m umd
  - npm run test -- -t es2015 -m umd
  - npm run test -- -t esnext -m umd

version: "{build}"
